# Generated by Django 2.1.2 on 2018-10-02 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=None, max_length=8, null=True, verbose_name='User-ID')),
                ('sippin', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='SIP PIN')),
                ('gastropin', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Gastro PIN')),
                ('rfid', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='RFID')),
                ('macaddress', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='MAC-Address')),
                ('clabpin', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='c-lab PIN')),
                ('preferred_email', models.CharField(default=None, max_length=1024, null=True, verbose_name='preferred e-mail address')),
                ('is_member', models.BooleanField(default=False, editable=False)),
                ('is_ldap_admin', models.BooleanField(default=False, editable=False)),
                ('is_circle_member', models.BooleanField(default=False, editable=False)),
                ('is_clab_member', models.BooleanField(default=False, editable=False)),
                ('is_cey_member', models.BooleanField(default=False, editable=False)),
                ('is_ceymaster', models.BooleanField(default=False, editable=False)),
                ('is_soundlab_member', models.BooleanField(default=False, editable=False)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
